### ISSUE TITLE
没有运行成功

### ISSUE THREAD

**Issue by lovebair2022** [cuijianxiong/cmscan#2]
我运行之后，显示错误：
Traceback (most recent call last):
  File "F:/struts2批量/Struts2批量识别/cmscan-master/cmscan.py", line 14, in <module>
    url = input('输入要识别的网址')
  File "<string>", line 1, in <module>
NameError: name 'www' is not defined

**Comment by k3rw1n** [comment]
我想你肯定是在2.7下运行的，这哥们的代码一看就是python3版本的
